### ISSUE TITLE
Subquery LIMIT clause not valid in mysql 5.6

### ISSUE THREAD

**Issue by ckuttruff** [ankane/delete_in_batches#3]
Firstly, thanks so much for the gem; really nice / simple usage.

I understand if there's not a reasonable workaround here, but with mysql 5.6 one hits this:
    ActiveRecord::StatementInvalid:                                                                                      
       Mysql2::Error: This version of MariaDB doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

Was looking at this workaround:
https://stackoverflow.com/a/7124492/1566623

Also, I imagine the performance impacts of moving the limit to the outside are clear... would it be possible to execute those are two separate queries so the subquery limit isn't hit?

Thanks!

**Comment by ankane** [comment]
Hey @ckuttruff, thanks for the detailed report and finding a solution. I was able to reproduce and fix on master.

**Comment by ckuttruff** [comment]
thanks so much for the speedy update!  And for your work on this and so many other projects (we use searchkick as well).

lol, so this is weird... mysql won't allow a limit within a subquery but it'll allow a limit within a subquery of a subquery?  A bit tired and not feeling very sharp so was a bit hazy on that.

This was the workaround that I had come up with, but you might see something I missed.  This should be DB agnostic:
https://gist.github.com/ckuttruff/dfb8aba30a936a6074f99621a392ee04

Thanks again for the prompt reply and for all your awesome open-source contributions.  I'll test this out sometime soon

**Comment by benrugg** [comment]
Hi @ankane - thanks for making this! It's exactly what I need. Any chance you could publish the latest version (with this fix included) to rubygems?

**Comment by ankane** [comment]
Released 0.1.0

**Comment by benrugg** [comment]
Thanks for the super quick response!
