### ISSUE TITLE
Optimizer plans should be documented

### ISSUE THREAD

**Issue by 64kramsystem** [ankane/delete_in_batches#4]
I had a look at the README and the code, but there is no documentation of how Rails plans the queries, and in turn, how the different databases do that.

The reason I'm writing this is that the code could (in theory) be simplified to:

```ruby
module DeleteInBatches
  def delete_in_batches(options = {})
    batch_size = options[:batch_size] || 10000

    while limit(batch_size).delete_all == batch_size
      yield if block_given?
    end
  end
end
```

Now, since the gem uses a slightly different strategy - it selects the PK values, and uses them in a giant `IN` - I suppose there are cases where this performs better than the straight `limit().delete_all()`, for critical cases, that is, multi-table deletes? Having them documented would clarify the design choice, which without context, is not clear.

For single-table deletes, I actually think `limit().delete_all()` may perform better, as it executes a single pass (as opposed to gathering the ids first, then executing the deletion).

Also, watch out with giant `IN`s - at least MySQL's optimizer may struggle with them.

**Comment by slimdave** [comment]
Yes, I cannot imagine circumstances in PostgreSQL or Oracle where a single `DELETE FROM ... WHERE ...` would be out-performed by either of the other two options, and the absence of benchmarks and (as you say) execution plans makes me doubt that this has any benefit at all.

I think a database administrator would look at either of the batch options with some degree of horror.

In Oracle you can be more friendly to other users on a busy OLTP system by repeatedly deleting with a LIMIT clause (no ordering though) until no rows are affected, but it would be slower than a single delete.

**Comment by ankane** [comment]
Hey, sorry for the delay.

@saveriomiroddi In terms of documentation, I'd be curious to see what you're thinking. Also, from what I can tell, `limit().delete_all` generates the same query as the gem:

```sql
DELETE FROM "tweets" WHERE "tweets"."id" IN (SELECT "tweets"."id" FROM "tweets" LIMIT 10000)
```

If there are better queries to use, happy to switch to them.

@slimdave I haven't tried Oracle, but just did a [very basic benchmark](https://gist.github.com/ankane/4e5f13244117e75fcd9836efabaa5df0) with Postgres (without tuning) and it looks like a single delete is consistently faster:

```txt
Iteration 1
delete_in_batches     69.3
AR in_batches         97.2
single delete         20.9

Iteration 2
delete_in_batches     35.1
AR in_batches         94.9
single delete         28.2

Iteration 3
delete_in_batches     32.2
AR in_batches        100.1
single delete         28.1

Iteration 4
delete_in_batches     31.2
AR in_batches         95.6
single delete         26.9

Iteration 5
delete_in_batches     47.1
AR in_batches        114.7
single delete         26.5
```

Not sure under what circumstances the batch approach was faster (created it in 2014 for Postgres and should have included benchmarks then). Will update the readme/description to reflect this.

**Comment by ankane** [comment]
I updated the benchmark script to include MySQL and MariaDB. It looks like `delete_in_batches` is the slowest method (facepalm).

MySQL (65,536,000 rows in DB)

```text
Iteration 1
delete_in_batches     20.0
AR in_batches          9.2
single delete          4.6

Iteration 2
delete_in_batches     12.3
AR in_batches         11.0
single delete          4.9

Iteration 3
delete_in_batches     12.0
AR in_batches         11.9
single delete          5.8

Iteration 4
delete_in_batches     13.0
AR in_batches         12.3
single delete          5.2

Iteration 5
delete_in_batches     13.3
AR in_batches         12.2
single delete          5.6
```

MariaDB (16,384,000 rows in DB)

```text
Iteration 1
delete_in_batches     31.9
AR in_batches          1.2
single delete          0.8

Iteration 2
delete_in_batches     29.0
AR in_batches          1.1
single delete          0.8

Iteration 3
delete_in_batches     28.6
AR in_batches          1.1
single delete          0.8

Iteration 4
delete_in_batches     30.2
AR in_batches          1.2
single delete          1.0

Iteration 5
delete_in_batches     32.2
AR in_batches          1.2
single delete          0.9
```

I've added a warning to the gem to use `in_batches().delete_all` instead for non-Postgres adapters. This project was archived after Active Record 4.2 reached EOL since Active Record 5 added support for batch deletes, but restored last year since it was faster than `in_batches().delete_all` for Postgres - definitely should have tested other databases :-/

Thank you both for bringing up this issue.
